import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="justify-content justify-end items-center justify-items-center gap-16 sm:pt-10 font-[family-name:var(--font-geist-sans)] flex flex-row pe-20 ps-20">
          <a href="/about/">About Me</a>
          <a href="/translations/">J-E Translations</a>
          <a href="/projects/">Code Projects</a>
        </nav>
        <main className="items-center justify-items-center min-h-screen pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)] flex flex-col">{children}</main>
      </body>
    </html>
  );
}
