import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="justify-content justify-end gap-16 pt-8 font-[family-name:var(--font-geist-sans)] flex flex-row pe-16 ps-16 dark:bg-gray-800 dark:text-white">
          <a href="/about/">About Me</a>
          <a href="/translations/">J-E Translations</a>
          <a href="/projects/">Code Projects</a>
        </nav>
        <main>{children}</main>
        <footer className="min-h-20 dark:text-white">
        </footer>
      </body>
    </html>
  );
}
